apiVersion: v1
kind: ConfigMap
metadata:
  name: colour-config
data:
  colour: green #ENV variable is set using  ConfigMap
---
apiVersion: v1
kind: Pod
metadata:
  name: pink
spec:
  containers:
    - name: pink
      image: mtinside/blue-green:blue
      env:
        - name: COLOUR
          valueFrom:
            configMapKeyRef:
              name: colour-config
              key: colour
