apiVersion: v1
data:
  index.html: "<html>\n    <head></head>\n    <body>\n        <p>Hello from Antonio!
    \U0001F44B</p>\n    </body>\n</html>\n"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: website
---
apiVersion: v1
kind: Pod
metadata:
  name: web
spec:
  containers:
    - name: web
      image: nginx:latest
      volumeMounts:
        - name: website-volume
          mountPath: /usr/share/nginx/html
  volumes:
    - name: website-volume
      configMap:
        name: website

