---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
# do not include replicas in the manifests if you want replicas to be controlled by HPA
  #replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          resources:
            requests:
              memory: 32Mi
              cpu: 250m
            limits:
              memory: 32Mi
              cpu: 250m
          livenessProbe:
            tcpSocket:
              port: 80
          readinessProbe:
            tcpSocket:
              port: 80
          startupProbe:
            tcpSocket:
              port: 80
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 80
          volumeMounts:
          - name: config
            mountPath: /usr/share/nginx/html/
      volumes:
      - name: config
        configMap:
          name: my-configmap      
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-deployment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  ports:
  - port: 80
  selector:
    app: nginx
  #type: LoadBalancer