apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: argo-cd
spec:
  project: default
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: wordpress
      targetRevision: "24.1.11"
      helm:
        valueFiles:
          - $values/apps/wordpress/values.yaml
    - repoURL: https://github.com/gudge25/kube-app-demo.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: wordpress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
