apiVersion: v1
kind: Service
metadata:
  name: example-loadbalanser
spec:
  selector:
    app: example-pod
  ports:
    - port: 9080
      targetPort: 80
  type: LoadBalancer #External  acces on port  9080