apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argo-cd
spec:
  project: default
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: rabbitmq
      targetRevision: "16.0.14"
      helm:
        valueFiles:
          - $values/APPS/helm-charts/prod/rabbitmq/values.yaml
    - repoURL: https://github.com/gudge25/kube-app-demo.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: rabbitmq
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
