# allowInsecureImages is required to allow the use of the bitnamilegacy.
global:
  security:
    allowInsecureImages: true

# Storage Longhorn
persistence:
  size: 1Gi
  storageClass: "longhorn"

# RabbitMQ Image
image:
  repository: bitnamilegacy/rabbitmq

# Init Container to set permissions on the volume
volumePermissions:
  image:
    repository: bitnamilegacy/rabbitmq

# ingress:
#   enabled: true
#   hostname: rabbitmq.example.com

# # Password persistence:
# auth:
#   username: user
#   password: '' # If you want to use a custom password, set this to a non-empty value. The password will be stored in a Kubernetes secret.
#   erlangCookie: '' # If you want to use a custom Erlang cookie, set this to a non-empty value. The cookie will be stored in a Kubernetes secret.

#TODO: move Passwords to Sealed Secrets
