apiVersion: batch/v1
kind: Job
metadata:
  name: myjob
spec:
  template:
    spec:
      containers:
      - name: fetch
        image: arm64v8/alpine
        command: ["/bin/sh",  "-c", "wget http://blue-green"]
      restartPolicy: Never  # do not restart
#Be sure that service        blue-green is  available
