apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argo-cd
spec:
  project: default
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: minio
      targetRevision: "16.0.10"
      helm:
        valueFiles:
          - $values/APPS/helm-charts/prod/minio/values.yaml
    - repoURL: https://github.com/gudge25/kube-app-demo.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  info:
    - name: URL
      value: https://www.min.io/
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
