---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openwa-config
  namespace: openwa
data:
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  AUTO_START_SESSIONS: "true"
  MEDIA_DOWNLOAD_ENABLED: "false"
  SEARCH_ENABLED: "false"
  ENABLE_SWAGGER: "true"
  SIMULATE_TYPING: "true"
  AUDIT_RETENTION_DAYS: "10"
  MESSAGE_RETENTION_DAYS: "90"

  DATABASE_HOST: "pgbouncer.pgbouncer.svc.cluster.local"
  DATABASE_NAME: "openwa"
  DATABASE_POOL_SIZE: "10"
  DATABASE_PORT: "5432"
  DATABASE_SSL: "false"
  DATABASE_TYPE: "postgres"
  DATABASE_USERNAME: "openwa"

  # ENGINE_TYPE: "whatsapp-web.js"
  ENGINE_TYPE: "baileys"
  BAILEYS_SYNC_FULL_HISTORY: "false"
  BAILEYS_BROWSER_NAME: "Mozilla/5.0"
  MINIO_BUILTIN: "false"
  POSTGRES_BUILTIN: "false"
  #PUPPETEER_HEADLESS: "true"
  #PUPPETEER_ARGS: "--no-sandbox --disable-setuid-sandbox --disable-dev-shm-usage --disable-gpu"
  QUEUE_ENABLED: "true"
  REDIS_BUILTIN: "false"
  REDIS_ENABLED: "true"
  #REDIS_HOST: "XXX.aivencloud.com"
  REDIS_PORT: "21274"
  SESSION_DATA_PATH: "./data/sessions"
  STORAGE_LOCAL_PATH: "./data/media"
  STORAGE_TYPE: "local"

  # DEBUG: "puppeteer:*"
  # NODE_DEBUG: "puppeteer:*"
  # DEBUG_COLORS: "0"
  # DEBUG_MAX_STRING_LENGTH: "null"
  # PUPPETEER_ARGS: "--no-sandbox --disable-setuid-sandbox --disable-dev-shm-usage --disable-gpu --enable-logging=stderr --v=1"
