# ---
# apiVersion: bitnami.com/v1alpha1
# kind: SealedSecret
# metadata:
#   name: pgbouncer-admin-secret
#   namespace: pgbouncer
#   annotations:
#     argocd.argoproj.io/sync-wave: "-1" # Sync before all other resources
# spec:
#   encryptedData:
#     adminPassword: AgBoMZuUFn3Dt+Bdvw60gxrgd67+kLTaO3HD0ytRyM1p6HYuiL4uF9RgLNx8ht+FoXHNMhCrXWVUf8HbBEA2n8v+zDjubdNFF/gcqnOFcyHZCi4ATu67BQH1/UP26/+bNEJwhn7K4al5lvELJJvyHiQ0x5Bd+s4M1oHTP+YwbZNt+lMRoDligwathWg4iliC1B0IkJea8jaP1dd4YQDuZ6u/i0ybR2isXx/u0Z8pjPqrJxbzxPEzUEQPgKMdbptu0EZtzR1ARigbRbhOS7OBN2v1+A4nbtw60rxM4drJvIpUhwKCkyZvB9PjONI1tupQqIVSWwWuIlo0MOipExpn8VQiATrCWVMhyVYYxjXA/hAb3T1S4o2YBA6HveAzmxVfxx3r6P7FGL4x+FjS9G3EAtdeJsQFnsqnrXJVji5MA0/OMXhM59E0jVjDbLNLnh1WgPgZfGL8E/XL1Y1PBwDhzrA3r1sOeULgnmYL5bio3pVIz2rQYEsRUpXsFGkhwsQ5N+z9Y1OtYXnhwJZqCu45tTTFPR4JtARUMi256Yy8/UxQGiRhufHVCTfQTef7HR6DBDkPzuVK0RB3LBC6vwltVBR7NtwCrvTeJalEoBoPN4E5s1KA41VhwOSkJsy36g9bSo9HFkER7g1yvwEOCUYq5fA43nyK/pQ8QpJvPehV8DrvDlm1sRf3QanODY+Ey+ngSvtsgII49/Jl1+Pt
#     adminUser: AgCTjdEOon2O6I1znBK8MOO4u9suU1Fcm440kusmvpgCYoU9dk5qtc/fSM6ta14q2fqf+3GPvT7wvmNrGTkemsFt1QLWUWhtz0tBfsRcLgSFXsqSmzAZMH5MHIahjycuChHf2/rvzdSggMCFXmdVu8srK7osa5xkrwK+A3/+p+wiThf71a0Toi59+bVNuBRrftsQIqNXdu0vOaIpmUmEUfSUgIGyGghCyMkGW2X3ejnxDxkCJKimyeZqBLn5jgCUFIexwB4U5QhAp+7irQINyoGi2O1YxRXLYNVTFeRJOxMmS8l8vFDySYqIMVSeqxlqeo7YfXTYl9ulb1ElTMOaR7rChhZg2VMyVHMwwsVwUa357Rc+uLg6fVnzC+FhC1zM/L1WB/4n682EcUl6GFunYLcU7QFBq66is/+RDLC2nXAJLTW3wNLo33pddsvpYy2e+OPq6/QMmmrT1UYQO3DD2uXdqDn4OimjOO8Z5ySYrbdCV9jFmI4ojSWb6FLiBbDlvaSVFF4kP5fbsaTkYMkOTxPc/TCyRL5pIfuO6rBcCt9hU5WRSp2DB02/Q+RmsJrPu57l2MuY5bUeZk7l0ANwG0PtLAIq+ZaN5m7o9KRRGh04sbGGtJU0ArGz+MyizbtVuop8SQRtRdthkXKNR2GeUFfE2siR3h7u8kfgZgHuNAl0l8I5qQnuxbh6/AxLPCEFQFDYJDeO8g==
#   template:
#     metadata:
#       name: pgbouncer-admin-secret
#       namespace: pgbouncer
#     type: Opaque
