---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pgbouncer-userlist-secret
  namespace: pgbouncer
  annotations:
    argocd.argoproj.io/sync-wave: "-1" # Sync before all other resources
spec:
  encryptedData:
    userlist.txt: AgB7qgd5nFuV+QOSEQHdcO2hHQI5SLygR2azQitR4ip2nyNXChoE5AA/LhSkLRoJFX+C7i1J3ybYG5YyYVImzMhn/efZuyuRyE63wvj4ZswyRxkm67hJezSss5iaGkwd3g4XvQYD3lIQ2J2qfvRNmvbfErdBZ6SL+YxAiPlHWzRaWIBAN+72XoO7aSXIub++G0yWFW/QRiSZZreu7AXki9FWEtEYO80SAcb6J9yOKFI8cbX/T3ThTuh/XhiF8Xdu/wRSJfSbLBwBcCTH1s/Hu6RxCdJM0ofhpb2nSDviM32aIs58kx/toy2bxNFK0Wj1rn5OcvN8iRI+nMIvCR6V0zm2DtACz/4DzC6LTMvvjAoZzEdER5Mzy5R82R1vJTV9qWVqSiHggZMWFOCU7rRsLyInlx5EnJB/1UiucR7tHRSsy1ctfpymFgBEzsjUmyyz7dquy51YRoMITj5yat4SL3WIAIN6RZ3YYcgWbavI03nrOa7SVkF5HFRKuVdxPflnw5tswCeU3VC1sKrXzw6QMFgvNr82EDuzvUG6hAQ+JEUYPF/AwlJFa0q0LYevBTzz0RxIuRKcZNKhm1pfM409dao86d6GSO9ywqlIXUqsgw8CT4+t4sm6uIwF61++jH8fTn/BsNrf0lQxLM74WTyKVnXmTMaSsXWTFjGTXSSSsE0H/MFMi3nlG2ysAbwAzeuDzAAiuJmZSyjtpHMjz272pDXB1KlmYNeHUkr7kYJTm5AVA2ofaTFy8EKgE74iQU6Z9o8kNvIygmv5OFfF4w==
  template:
    metadata:
      name: pgbouncer-userlist-secret
      namespace: pgbouncer
    type: Opaque
