---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pgbouncer-userlist-secret
  namespace: pgbouncer
  annotations:
    argocd.argoproj.io/sync-wave: "-1" # Sync before all other resources
spec:
  encryptedData:
    userlist.txt: AgAVenI5xQo7+vLiQAMPKK+XS60GMLc4Sy37DQczClwwCVkYgRECltlzxTzzf9xlxgdV04z/oVpH8crR2cJr1TTDG6tKYXFCacsdfFgJkzpE69CSZekVNmztMoHTg+cW/rIeJXLh+1rHbpgBrMqpyAiw1ENoBzqfrmawaGD7wjAzzdSOGjU2xj+Bsz19jfh3qCky7nVVFGqvTEoBJxyn0LjXyNOmNxZkvzf3bJCBHgcJFiCFKidUcnPg4n/aZBpeYjTEdm1p6z4OBSP1zQ4VTldl5p0aYZ/IIsjfQ+soY0LUQETiFKeRfp1pzjFsGe2OVoMomQ45Ug8i8p/prqcw42Yvs+Lql/JCSNc1G0/Y4YMndCJgjMzCbrrwBc1LjL5K+aGEthE1QsvhTBgQUDrmwCI9zzeLtb1zhzk1lyGGKDv6PSZUzC1+HUKC/BxMEWkTSuR9XPC1qANSfgWT3/Zltc7b7flYPvVyjjBR6nUVv4ydCa2Fa6IqNRMVTzZNBh8WEH+V2IzIfRmqsiILlssQnQPtIgReQlZxSkDzFl0hAnllhKOpQbTXZbcPmsxQudv2PeRZVQ5AbP2IsFhqH0OC1z+QbHOMsyob07n+2kfOWanU534nJXb5aVqiFnpZ1LyUO70uoma3URxBPOYAah22g3m02BkIA6dVKeien5NJJ6uJzwG54VNk2ojpCJCK4K+d4Hhl3nVyIbHWVrbcmYgbPMNRC8/0wPEFwD15r+zsP37211I9vc0J2yOvNo0PyFXKcdOXp6qj0yDb6w==
  template:
    metadata:
      name: pgbouncer-userlist-secret
      namespace: pgbouncer
    type: Opaque
