---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pgbouncer-userlist-secret
  namespace: pgbouncer
  annotations:
    argocd.argoproj.io/sync-wave: "-1" # Sync before all other resources
spec:
  encryptedData:
    userlist.txt: AgAnHac/gJdRsok1lWRuLiyJeKlBRaZApZvcAHtnqzXVhK3XMaLo7Bavv3dmu7CAkzIp5hib5UipflvRa2cAhmLVIaF93WoNKhYDPnO9/z92mTFaIYc4JBUPAr8t0jNRW4tm5ozj7ElXPQ1RPQwPIAbjgdN+7GJ9pzWb0XfSvXrQEMzNgm/PLiNjyXolRYdPGC+KZ2SjgoCfZ2U1OVDpKQxL5jC78TcUTZO7/2M/s1gTo8A6FZ9oZ/DtiSEwQ1uRIruPpDpuNamsUyeQgP/5gdsR4KF2aQKkLognrCWve1X1mvcpOX7urIJlcId/u9IISEwPSOLcBiQ3Jt9EDy9D16W0CvgYKlTpcXMvHQyXFPO+/N/7NzIlrWcL51tQ/Qvs0IVrfJkMKllg+tC1la/pTdQe86UGo61nx1GeXTpIMXgjkTw4SVY7h/BSDqtZy/NyqAEPcPK6v4c4X4ritBxuu2RaZ5J7fkxOwP9g1ZWrOWyOd6wMF0ND7aCqs2siHXmPapcRjDaVdJYUqjCxQMKVwZf10jq+17Z27wh8avZmAE2mvWIco6JCdt1HIAsXD1a14PU64UldJlKtcOQaT8KremdFxiFOb646YMWrl8e7QFPtZFBUNsXCEzBDSLOd7v1YrHdViZsuNErGLkVgltIXSMq8dH4a0cQxw/uE4lEmBw7fuAKqH4HFqyyiH9ROugpsM77RrGFhtoYS9ogqEIMmTg1vzKfBlqSRSoKxlXp0QQ7+iosdYw==
  template:
    metadata:
      name: pgbouncer-userlist-secret
      namespace: pgbouncer
    type: Opaque
