# Before you need to create a secret with a  token in namespace cloudflared
# kubectl create secret generic cloudflared-token --from-literal=token='' -n cloudflared
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  labels:
    app: cloudflared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:latest
          args:
            - tunnel
            - --no-autoupdate
            - run
            - --token
            - "$(TOKEN)"
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflared-token
                  key: token